Repository U-Final/U-Hyu-fe, pull requests merged in 2025-08, with the labels that each got.

#148 [FIX][UHYU-322] 관리자 페이지 브랜드 관리 접근 에러
  src/features/admin/api/adminApi.ts
  src/features/admin/api/endpoints.ts
  src/features/admin/api/mockData.ts
  src/features/admin/api/types.ts
  src/features/admin/components/brand/AdminBrandCard.tsx
  src/features/admin/components/brand/AdminBrandForm.tsx
  src/features/admin/components/brand/AdminBrandList.tsx
  src/features/admin/components/brand/AdminBrandModal.tsx
  src/features/admin/components/brand/BrandForm.tsx
  src/features/admin/components/brand/BrandListItem.tsx
  src/features/admin/components/brand/NewAdminBrandList.tsx
  src/features/admin/components/common/CategoryFilter.tsx
  src/features/admin/components/common/StatsSummaryCards.tsx
  src/features/admin/components/stats/BookmarkChart.tsx
  src/features/admin/components/stats/FilteringChart.tsx
  src/features/admin/components/stats/MembershipChart.tsx
  src/features/admin/components/stats/RecommendChart.tsx
  src/features/admin/constants/brandCategoryMapping.ts
  src/features/admin/constants/brandConfigs.ts
  src/features/admin/constants/categories.ts
  src/features/admin/constants/index.ts
  src/features/admin/hooks/index.ts
  src/features/admin/hooks/useAdminBrandQuery.ts
  src/features/admin/index.ts
  src/features/admin/types/component.ts
  src/features/admin/types/index.ts
  src/pages/admin/AdminPage.tsx
  src/shared/msw/handlers/admin.ts
  yarn.lock
Labels: 🐞 버그

#153 [FEAT][UHYU-67] OAuth 리다이렉트 처리
  src/shared/client/axiosClient.ts
Labels: ✨ 기능구현

#157 [FIX][UHYU-67] 로그인 하고 돌아왔을 때 로그인 여부 적용되게 수정
  src/shared/components/AppInitializer.tsx
  src/shared/hooks/useTabFocusAuth.ts
Labels: 🐞 버그

#155 [FEAT][UHYU-334] 즐겨찾기 조회 MSW 및 즐겨찾기 토글 버튼 추가
  src/features/kakao-map/api/endpoints.ts
  src/features/kakao-map/api/mapApi.ts
  src/features/kakao-map/components/bookmark/BookmarkButton.tsx
  src/features/kakao-map/components/bookmark/BookmarkControlContainer.tsx
  src/features/kakao-map/components/marker/FavoriteMarker.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/components/marker/MyMapMarker.tsx
  src/features/kakao-map/hooks/useMapData.ts
  src/features/kakao-map/store/MapStore.ts
  src/features/kakao-map/store/types.ts
  src/features/mymap/constants/mymapColor.ts
  src/index.css
  src/pages/map/MapPage.tsx
  src/shared/msw/handlers/map.ts
Labels: ✨ 기능구현

#159 [BUG][UHYU-342] 제휴처 리스트 , 삭제 및 중복제거
  src/features/benefit/utils/formatGradeDescriptions.tsx
Labels: 🐞 버그

#161 [FIX][UHYU-344] 온보딩 요청 URL 변경
  src/features/user/api/endpoints.ts
  src/pages/user/extra-info/ExtraInfo.tsx
  src/shared/msw/handlers/user.ts
Labels: 🐞 버그

#164 [FEAT][UHYU-327] My Map 지도 조회 (UUID 기반,비회원) MSW 및 공유지도 비회원 조회 구현
  src/features/mymap/api/endpoint.ts
  src/features/mymap/api/mymapApi.ts
  src/features/mymap/components/bottom-sheet/MymapUuid.tsx
  src/features/mymap/hooks/index.ts
  src/features/mymap/hooks/useMyMapUuidQuery.ts
  src/shared/msw/handlers/mymap.ts
Labels: ✨ 기능구현

#168 [FIX] 인증인가 관련 부분 fix
  src/shared/store/userStore.ts
Labels: 🐞 버그

#167 [BUG][UHYU-346] max-w-md 삭제
  src/features/mymap/components/bottom-sheet/MyMapList.tsx
  src/features/mymap/components/list/MymapBody.tsx
Labels: 🐞 버그

#165 [FIX][UHYU-343] 모바일 화면일때 인포윈도우 클릭시 닫히는 버그, 개발용 콘솔로그 제거, 세부 디테일 작업
  src/features/kakao-map/api/keywordSearchApi.ts
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/kakao-map/components/ManualSearchButton.tsx
  src/features/kakao-map/components/MapContainer.tsx
  src/features/kakao-map/components/MapControlsContainer.tsx
  src/features/kakao-map/components/MapDragBottomSheet.tsx
  src/features/kakao-map/components/SidebarSheet.tsx
  src/features/kakao-map/components/bookmark/BookmarkControlContainer.tsx
  src/features/kakao-map/components/card/StoreDetailCard.tsx
  src/features/kakao-map/components/controls/MapControlsContainer.tsx
  src/features/kakao-map/components/layout/steps/BrandSelectContent.tsx
  src/features/kakao-map/components/location/LocationButton.tsx
  src/features/kakao-map/components/location/LocationControlContainer.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/components/marker/StoreInfoWindow.tsx
  src/features/kakao-map/components/search/MapSearchInput.tsx
  src/features/kakao-map/context/MapUIContext.tsx
  src/features/kakao-map/hooks/useKeywordSearch.ts
  src/features/kakao-map/hooks/useManualSearch.ts
  src/features/kakao-map/hooks/useMapData.ts
  src/features/kakao-map/hooks/useMapInteraction.ts
  src/features/kakao-map/hooks/useMapUI.ts
  src/features/kakao-map/hooks/useSearchMarkers.ts
  src/pages/map/MapPage.tsx
  src/pages/user/extra-info/ExtraInfo.tsx
  src/routes/AppRoutes.tsx
  src/shared/components/index.ts
  src/shared/components/route/ProtectedRoute.tsx
  src/shared/msw/handlers/map.ts
  src/shared/msw/handlers/mymap.ts
  src/shared/msw/handlers/user.ts
  src/shared/store/userStore.ts
  src/shared/utils/categoryMapper.ts
  src/shared/utils/scrollRestore.ts
  src/shared/utils/viewport.ts
Labels: 🐞 버그

#169 [FIX] onboardingPage export 명 수정
  src/pages/user/extra-info/ExtraInfo.tsx
Labels: 🐞 버그

#162 [FEAT][UHYU-341] 관리자 페이지-브랜드 관리 api 재설정
  src/features/admin/api/adminApi.ts
  src/features/admin/api/endpoints.ts
  src/features/admin/api/mockData.ts
  src/features/admin/api/types.ts
  src/features/admin/components/brand/AdminBrandCard.tsx
  src/features/admin/components/brand/AdminBrandDeleteModal.tsx
  src/features/admin/components/brand/AdminBrandForm.tsx
  src/features/admin/components/brand/AdminBrandList.tsx
  src/features/admin/components/brand/AdminBrandModal.tsx
  src/features/admin/components/brand/AdminBrandPagination.tsx
  src/features/admin/components/brand/BrandForm.tsx
  src/features/admin/components/brand/BrandListItem.tsx
  src/features/admin/components/brand/NewAdminBrandList.tsx
  src/features/admin/components/brand/index.ts
  src/features/admin/components/common/EmptyState.tsx
  src/features/admin/components/common/StatsSummaryCards.tsx
  src/features/admin/components/common/index.ts
  src/features/admin/components/stats/BookmarkChart.tsx
  src/features/admin/components/stats/FilteringChart.tsx
  src/features/admin/components/stats/MembershipChart.tsx
  src/features/admin/components/stats/RecommendChart.tsx
  src/features/admin/constants/categories.ts
  src/features/admin/hooks/index.ts
  src/features/admin/hooks/useAdminBrandMutation.ts
  src/features/admin/hooks/useAdminBrandQuery.ts
  src/features/admin/hooks/useAdminStatsQuery.ts
  src/features/admin/index.ts
  src/features/admin/types/component.ts
  src/features/admin/types/index.ts
  src/features/kakao-map/constants/categoryMapping.ts
  src/features/kakao-map/types/category.ts
  src/features/mypage/api/mockData.ts
  src/pages/admin/AdminPage.tsx
  src/shared/msw/handlers/admin.ts
Labels: ✨ 기능구현

#176 [HOTFIX] user 로컬스토리지 저장에서 세션스토리지 저장으로 변경
  src/shared/store/userStore.ts
Labels: 🐞 버그

#172 [BUG][UHYU-358] MapControlsContainer의 위치 기준을 MapContent로 변경
  src/features/kakao-map/components/controls/MapControlsContainer.tsx
Labels: 🐞 버그

#178 [REFACTOR][UHYU-355] bacode modal 수정
  src/shared/components/BaseLayout.tsx
  src/shared/components/bottom_navigation/BottomNavigation.tsx
  src/shared/components/bottom_navigation/barcode/BarcodeBottomSheet.tsx
  src/shared/components/bottom_navigation/barcode/contents/GuestBarcodeContent.tsx
  src/shared/components/bottom_navigation/barcode/contents/LoggedInBarcodeContent.tsx
  src/shared/components/sidebar/LoggedInContent.tsx
  src/shared/store/barcodeStore.ts
Labels: ♻️리펙토링

#174 [FEAT][UHYU-347] keyword 검색 debouncing 및 자동 검색 및 검색결과 없을 때 처리 (환경변수 추가)
  src/features/kakao-map/components/MapContainer.tsx
  src/features/kakao-map/components/MapControlsContainer.tsx
  src/features/kakao-map/components/layout/MapTopControls.tsx
  src/features/kakao-map/components/search/KeywordSearchContainer.tsx
  src/features/kakao-map/components/search/SearchResultList.tsx
  src/features/kakao-map/components/search/SearchResultSummary.tsx
  src/features/kakao-map/hooks/useKeywordSearch.ts
  src/pages/map/MapPage.tsx
  src/vite-env.d.ts
Labels: ✨ 기능구현

#180 [REFACTOR][UHYU-349] 마이페이지 관심 브랜드 api 연결 및 활동내역 UI
  src/features/mypage/api/mockData.ts
  src/features/mypage/api/mypageApi.ts
  src/features/mypage/components/ActivityBenefit.tsx
  src/features/mypage/components/ActivityBrands.tsx
  src/features/mypage/components/ActivityFavorite.tsx
  src/features/mypage/components/MyPageBrand.tsx
  src/shared/components/AppInitializer.tsx
Labels: ♻️리펙토링

#181 [FIX][UHYU-362] 마이페이지 즐겨찾기 전부 제거 시 발생하는 에러 해결
  src/features/mypage/api/mockData.ts
  src/features/mypage/api/mypageApi.ts
  src/features/mypage/components/ActivityFavorite.tsx
Labels: 🐞 버그

#179 [UHYU-360][FEAT] 마커 클릭, 바텀시트 매장 클릭시 줌 레벨 4로 고정
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/hooks/useMapInteraction.ts
Labels: ✨ 기능구현

#182 [FEAT][UHYU-361] 위치버튼 반응형으로 높이 설정 및 스타일 개선
  src/features/kakao-map/components/controls/MapControlsContainer.tsx
  src/features/kakao-map/components/location/CurrentLocationMarker.tsx
  src/features/kakao-map/components/location/LocationButton.tsx
  src/features/kakao-map/components/location/LocationControlContainer.tsx
  src/features/kakao-map/components/location/index.ts
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/store/MapStore.ts
  src/features/kakao-map/store/types.ts
Labels: ✨ 기능구현

#185 [FEAT][UHYU-364] 마이페이지 마커 클릭 수 api 추가 및 디자인 개선
  src/features/mypage/api/mockData.ts
  src/features/mypage/api/mypageApi.ts
  src/features/mypage/api/types.ts
  src/features/mypage/components/ActivityBenefit.tsx
  src/features/mypage/components/ActivityBrands.tsx
  src/features/mypage/components/ActivityFavorite.tsx
  src/features/mypage/types/mockActivity.ts
  src/index.css
Labels: ✨ 기능구현

#187 [FEAT][UHYU-359] 즐겨찾기, 내위치 보기 버튼 이동 및 공유지도 목록 패딩추가
  src/features/kakao-map/components/controls/MapControlsContainer.tsx
  src/features/mymap/api/mockData.ts
  src/features/mymap/components/bottom-sheet/MymapUuid.tsx
Labels: 🐞 버그

#188 [FIX][UHYU-370] 마커 클릭 수 조회 api 타입 설정
  src/features/mypage/api/types.ts
  src/features/mypage/components/ActivityBenefit.tsx
  src/features/mypage/components/ActivityBrands.tsx
  src/features/mypage/types/mockActivity.ts
Labels: 🐞 버그

#191 [FEAT][UHYU- 368] google analytics 구축
  package.json
  src/App.tsx
  src/features/barcode/components/VisitConfirmSection.tsx
  src/features/benefit/components/BenefitList.tsx
  src/features/kakao-map/components/marker/BrandMarker.tsx
  src/features/kakao-map/components/search/MapSearchInput.tsx
  src/features/mymap/components/AddMyMapButton.tsx
  src/shared/components/bottom_navigation/BottomNavigation.tsx
  src/shared/components/modals/LoginModal.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useGA.ts
  src/shared/utils/gaTracker.ts
  src/vite-env.d.ts
  yarn.lock
Labels: ✨ 기능구현

#192 [BUG][UHYU-372] QA 반영
  src/features/benefit/components/CheckBoxList.tsx
  src/features/kakao-map/components/MapControlsContainer.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/store/MapStore.ts
  src/features/kakao-map/store/types.ts
  src/features/mymap/components/modal/AddStoreModal.tsx
  src/pages/map/MapPage.tsx
Labels: 🐞 버그

#193 [FEAT][UHYU-375] 스토어 타입 brandId 값 받아오게 추가
  src/features/kakao-map/types/store.ts
  src/features/recommendation/api/recommendedStoresApi.ts
  src/features/recommendation/components/RecommendedCard.tsx
  src/features/recommendation/hooks/useRecommendMutation.ts
  yarn.lock
Labels: ✨ 기능구현

#195 [FEAT][UHYU-379] 추천카드에서 싫어요 버튼 클릭시 모달창 뜨게 수정
  src/features/recommendation/components/ConfirmExcludeModalContent.tsx
  src/features/recommendation/components/RecommendedCard.tsx
  src/features/recommendation/hooks/useRecommendMutation.ts
Labels: ✨ 기능구현

#197 [FIX][UHYU-385] 로그인 에러 해결
  src/features/recommendation/components/RecommendedStoreListLoggedIn.tsx
Labels: 🐞 버그

#202 [CHOR][UHYU-390] 여러 컴포넌트 컬러 프라이머리 적용 및 온보딩 사용자 안내 문구 추가
  src/features/extra-info/components/PrimaryButton.tsx
  src/features/extra-info/components/StepContent.tsx
  src/features/kakao-map/components/ManualSearchButton.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/components/search/KeywordSearchContainer.tsx
  src/features/kakao-map/components/ui/MapZoomLevelIndicator.tsx
  src/features/kakao-map/hooks/useMapData.ts
  src/features/kakao-map/store/MapStore.ts
  src/features/kakao-map/store/types.ts
  src/features/kakao-map/utils/zoomUtils.ts
  src/features/mypage/components/ActivityBrands.tsx
  src/pages/map/MapPage.tsx
  src/pages/user/extra-info/ExtraInfo.tsx
  src/shared/components/bottom_navigation/BarcodeItem.tsx
  src/shared/components/bottom_navigation/BottomNavigation.tsx
  src/shared/components/bottom_navigation/barcode/BarcodeBottomSheet.tsx
  src/shared/components/brand_grid/BrandLogo.tsx
  src/shared/components/modals/LoginModal.tsx
  src/shared/hooks/useScrollPrevention.ts
  src/shared/msw/handlers/map.ts
  src/shared/utils/gaTracker.ts
  src/shared/utils/scrollUtils.ts
  yarn.lock
Labels: ♻️리펙토링

#203 [FEAT][UHYU-392] lottie 기반 바텀 시트 guide 기능 추가 및 지도 이벤트 버그 수정
  package.json
  public/lottie/swipe_up.json
  src/features/kakao-map/components/layout/MapTopControls.tsx
  src/features/kakao-map/components/ui/MapZoomLevelIndicator.tsx
  src/pages/map/MapPage.tsx
  src/shared/components/tutorial/BottomSheetTutorial.tsx
  src/shared/hooks/useFirstVisit.ts
  yarn.lock
Labels: ✨ 기능구현, 🐞 버그

#207 [BUG][UHYU-400]지도 bottomsheet 중간 설정 및 튜토리얼 위치, 멘트 수정
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/shared/components/tutorial/BottomSheetTutorial.tsx
Labels: 🐞 버그

#206 [REFACTOR][UHYU-386] 마커 디자인 개선 및 어드민 버그 수정
  package.json
  src/features/admin/api/mockData.ts
  src/features/admin/api/types.ts
  src/features/admin/components/brand/AdminBrandCard.tsx
  src/features/admin/components/brand/AdminBrandForm.tsx
  src/features/admin/components/brand/AdminBrandList.tsx
  src/features/admin/components/common/AdminToggleTabs.tsx
  src/features/admin/components/common/BrandListSkeleton.tsx
  src/features/admin/components/common/StatsSummaryCards.tsx
  src/features/kakao-map/components/marker/BrandMarker.tsx
  src/pages/admin/AdminPage.tsx
  yarn.lock
Labels: ♻️리펙토링

#213 [BUG][UHYU-407] QA 반영
  index.html
  public/icon/favicon-16x16.png
  public/icon/favicon-32x32.png
  public/icon/favicon-96x96.png
  public/icon/favicon.ico
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/pages/AuthSuccess.tsx
  src/pages/map/MapPage.tsx
  src/shared/components/filter_tabs/FilterTabs.variants.ts
  src/shared/components/tutorial/BottomSheetTutorial.tsx
Labels: 🐞 버그

#212 [REFACTOR][UHYU-408] 바텀 시트 추천 카드 디자인 개선
  src/features/kakao-map/components/controls/MapZoomLevelIndicator.tsx
  src/features/kakao-map/components/layout/MapTopControls.tsx
  src/features/recommendation/components/RecommendedCard.tsx
  src/features/recommendation/components/RecommendedStoreListLoggedIn.tsx
  src/features/recommendation/components/ToggleButton.tsx
  src/index.css
  yarn.lock
Labels: ♻️리펙토링

#215 [FIX][UHYU-410] 키워드 검색 결과 z 인덱스 조정 및 재검색 버튼 바텀시트와 동기화
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/kakao-map/components/MapControlsContainer.tsx
  src/features/kakao-map/components/controls/ManualSearchButton.tsx
  src/features/kakao-map/components/controls/MapControlsContainer.tsx
  src/features/kakao-map/components/controls/MapDragBottomSheet.tsx
  src/features/kakao-map/components/controls/MapZoomLevelIndicator.tsx
  src/features/kakao-map/components/layout/MapTopControls.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/components/search/KeywordSearchContainer.tsx
  src/features/kakao-map/constants/regions.ts
  src/features/kakao-map/context/MapUIContext.tsx
  src/features/recommendation/components/RecommendStoreInfoWindow.tsx
  src/features/recommendation/components/RecommendedCard.tsx
  src/features/recommendation/components/RecommendedStoreListLoggedIn.tsx
  src/features/recommendation/components/ToggleButton.tsx
Labels: ✨ 기능구현, ♻️리펙토링, 🐞 버그

#218 [FIX][UHYU-411] 네비게이션바 높이, mymap, 혜택 상세보기 스타일 수정
  src/features/benefit/components/BrandDetailModal.tsx
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/kakao-map/components/layout/StoreListContent.tsx
  src/features/kakao-map/components/layout/steps/BrandSelectContent.tsx
  src/features/kakao-map/components/layout/steps/CategorySelectContent.tsx
  src/features/mymap/components/bottom-sheet/MyMapList.tsx
  src/features/mymap/components/bottom-sheet/MymapUuid.tsx
  src/features/mymap/components/list/MymapBody.tsx
  src/features/mymap/components/list/MymapHeader.tsx
  src/shared/components/bottom_navigation/BarcodeItem.tsx
  src/shared/components/bottom_navigation/BottomNavigation.tsx
  src/shared/store/index.ts
Labels: ♻️리펙토링

#220 [REFACTOR][UHYU-417] 마이페이지 QA 사항 반영
  src/features/mypage/components/ActivityBrands.tsx
  src/features/mypage/components/MyPageHeader.tsx
  src/features/mypage/components/MyPageMembership.tsx
  src/features/mypage/components/MyPageUserInfo.tsx
  src/shared/components/skeleton/mypage/ActivityBrandsDetailSkeleton.tsx
  yarn.lock
Labels: ♻️리펙토링

#219 [FIX][STYLE][UHYU-412] 추천 카드 및 추천 인포윈도우 버그 및 Map UI 사용자 경험 개선
  src/features/kakao-map/api/mockData.ts
  src/features/kakao-map/components/bookmark/BookmarkButton.tsx
  src/features/kakao-map/components/controls/MapControlsContainer.tsx
  src/features/kakao-map/components/controls/MapZoomLevelIndicator.tsx
  src/features/kakao-map/components/layout/BottomSheetToggleButton.tsx
  src/features/kakao-map/components/layout/MapTopControls.tsx
  src/features/kakao-map/components/layout/RegionFilterDropdown.tsx
  src/features/kakao-map/components/location/LocationButton.tsx
  src/features/kakao-map/components/search/MapSearchInput.tsx
  src/features/recommendation/api/recommendedStores.mock.ts
  src/features/recommendation/components/RecommendStoreInfoWindow.tsx
  src/features/recommendation/components/RecommendedCard.tsx
  src/shared/components/filter_tabs/FilterTabs.tsx
  src/shared/components/filter_tabs/FilterTabs.variants.ts
  src/shared/components/sidebar/SidebarSheet.tsx
Labels: 🐞 버그

#222 [FEAT][UHYU-421] 홈화면 로그인 모달 연동 추가 및 mymap 빈 리스트 이미지 처리
  public/images/empty/empty-state-map.png
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/mymap/components/bottom-sheet/MyMapList.tsx
  src/features/mymap/components/list/MymapBody.tsx
  src/features/recommendation/components/RecommendedStoreListGuest.tsx
Labels: ✨ 기능구현

#224 [SETTING][UHYU-420] vercel 루트 도메인으로 리다이렉트 www -> non www
  src/features/kakao-map/context/MapUIContext.tsx
  vercel.json
Labels: 📚 문서화

#223 [FIX][UHYU-419] 관리자 페이지 수정 메소드 변경 및 마이페이지 반응형, 토글 버튼 skicky 효과 개선
  src/features/admin/api/adminApi.ts
  src/features/admin/api/types.ts
  src/features/admin/components/brand/AdminBrandForm.tsx
  src/features/admin/components/common/AdminToggleTabs.tsx
  src/features/mypage/components/ActivityFavorite.tsx
  src/features/mypage/components/ActivityTabs.tsx
  src/shared/components/filter_tabs/FilterTabs.tsx
Labels: 🐞 버그

#226 [FIX] 바코드 이미지 없고 모달 켰을때 토스트 에러처리
  src/shared/client/axiosClient.ts
Labels: ✨ 기능구현

#225 [FIX][UHYU-424] 추천 카드 및 인포 윈도우 디자인 및 버그 개선
  src/features/kakao-map/components/layout/StoreListContent.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/recommendation/components/RecommendedCard.tsx
  src/features/recommendation/components/RecommendedStoreListLoggedIn.tsx
Labels: 🐞 버그

#231 [BUG][UHYU-429] delete: JavaScript를 통한 동적 viewport 재설정 로직 제거
  index.html
Labels: 🐞 버그

#227 [REFACTOR][UHYU-425] 페이지 레이아웃 여백 추가
  src/index.css
  src/shared/components/BaseLayout.tsx
  src/shared/components/sidebar/SidebarSheet.tsx
Labels: ♻️리펙토링

#234 [BUG][UHYU-431] 매장 추가 모달 refetch 및 줄바꿈 처리 추가
  src/features/benefit/utils/formatUsageText.ts
  src/features/mymap/components/modal/AddStoreModal.tsx
Labels: 🐞 버그

#233 Update README.md
  README.md
Labels: 📚 문서화

#238 [REFACTOR][UHYU-434] 마이페이지 및 관리자 페이지 리드미 보완
  .claude/agents/tech-lead.md
  README.md
Labels: ♻️리펙토링
