Repository U-Final/U-Hyu-fe, pull requests merged in 2025-07, with the labels that each got.

#2 Merge Into develop
  .github/pull_request_template.md
  .github/workflows/chromatic.yml
  .github/workflows/develop.yml
  .husky/pre-commit
  .husky/pre-push
  chromatic.config.json
  index.html
  package.json
  public/favicon/android-icon-144x144.png
  public/favicon/android-icon-192x192.png
  public/favicon/android-icon-36x36.png
  public/favicon/android-icon-48x48.png
  public/favicon/android-icon-72x72.png
  public/favicon/android-icon-96x96.png
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-57x57.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/apple-icon-precomposed.png
  public/favicon/apple-icon.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/favicon/favicon.ico
  public/favicon/manifest.json
  public/favicon/ms-icon-144x144.png
  public/favicon/ms-icon-150x150.png
  public/favicon/ms-icon-310x310.png
  public/favicon/ms-icon-70x70.png
  public/fonts/Pretendard-Black.otf
  public/fonts/Pretendard-Bold.otf
  public/fonts/Pretendard-ExtraBold.otf
  public/fonts/Pretendard-ExtraLight.otf
  public/fonts/Pretendard-Light.otf
  public/fonts/Pretendard-Medium.otf
  public/fonts/Pretendard-Regular.otf
  public/fonts/Pretendard-SemiBold.otf
  public/fonts/Pretendard-Thin.otf
  src/App.tsx
  src/index.css
  tailwind.config.js
  vite.config.ts
  yarn.lock
Labels: ✨ 기능구현

#7 [FEAT][UHYU-126] SearchInput 컴포넌트 생성 및 Storybook 적용
  src/components/search_input/SearchInput.tsx
  src/components/search_input/SearchInput.types.ts
  src/components/search_input/SearchInputVariants.ts
  src/components/search_input/__stories__/SearchInput.stories.ts
  yarn.lock
Labels: ✨ 기능구현

#9 [FEAT][UHYU-107] filterTabs 컴포넌트 생성 및 Storybook 적용
  .storybook/preview.ts
  src/components/filter_tabs/FilterTabs.tsx
  src/components/filter_tabs/FilterTabs.types.ts
  src/components/filter_tabs/FilterTabs.variants.ts
  src/components/filter_tabs/__stories__/FilterTabs.stories.ts
  src/index.css
Labels: ✨ 기능구현

#12 [FEAT][UHYU-139] bottom-sheet 모달 공통 컴포넌트 구현
  .storybook/main.ts
  package.json
  src/shared/components/bottom_sheet/BaseBottomSheet.tsx
  src/shared/components/bottom_sheet/NavigationBottomSheet.tsx
  src/shared/components/bottom_sheet/SelectionBottomSheet.tsx
  src/shared/components/bottom_sheet/__stories__/BaseBottomSheet.stories.tsx
  src/shared/components/bottom_sheet/__stories__/NavigationBottomSheet.stories.tsx
  src/shared/components/bottom_sheet/__stories__/SelectionBottomSheet.stories.tsx
  src/shared/components/bottom_sheet/bottomSheet.type.ts
  src/shared/components/bottom_sheet/hooks/useBottomSheetNavigation.ts
  src/shared/components/bottom_sheet/hooks/useMultiSelect.ts
  src/shared/components/buttons/ButtonBase.tsx
  src/shared/components/buttons/GhostButton.tsx
  tsconfig.tsbuildinfo
  yarn.lock
Labels: ✨ 기능구현

#17 [FEAT][UHYU-147] pagination 컴포넌트 구현
  src/index.css
  src/pages/benefit/BenefitPage.tsx
  src/pages/benefit/components/Pagination.tsx
  src/pages/benefit/components/PaginationButton.tsx
  src/pages/benefit/components/PaginationButton.types.ts
  src/pages/benefit/types/Pagination.types.ts
  src/routes/AppRoutes.tsx
  src/shared/constants/path.ts
Labels: ✨ 기능구현

#23 [FEAT][UHYU-31] common modal
  src/features/extra-info/components/StepContent.tsx
  src/routes/AppRoutes.tsx
  src/routes/path.ts
  src/shared/components/buttons/NavButton.tsx
  src/shared/components/buttons/__stories__/NavButton.stories.tsx
  src/shared/components/modals/BaseModal.tsx
  src/shared/components/modals/LoginModal.tsx
  src/shared/components/modals/ModalRoot.tsx
  src/shared/components/modals/__stories__/BaseModal.stories.tsx
  src/shared/components/modals/__stories__/LoginModal.stories.tsx
  src/shared/store/modalStore.ts
Labels: ✨ 기능구현

#24 [UHYU-29] 공통 카드 컴포넌트 구현(기본, 브랜드카드, 브랜드카드+즐겨찾기)
  src/index.css
  src/shared/components/cards/BrandCard.tsx
  src/shared/components/cards/BrandWithFavoriteCard.tsx
  src/shared/components/cards/CardBase.tsx
  src/shared/components/cards/__stories__/BrandCard.stories.tsx
  src/shared/components/cards/__stories__/BrandWithFavoriteCard.stories.tsx
  src/shared/components/cards/__stories__/CardBase.stories.tsx
Labels: ✨ 기능구현

#28 [FEAT][UHYU-170] 공통 Drag Bottom Sheet 구현
  package.json
  src/shared/components/bottom_navigation/BottomNavigation.tsx
  src/shared/components/bottom_sheet/DragBottomSheet.tsx
  src/shared/components/bottom_sheet/__stories__/DragBottomSheet.stories.tsx
  yarn.lock
Labels: ✨ 기능구현

#32 [FEAT][UHYU-164] 이미지 바코드 크롭 기능 및 바텀시트 UI 구현
  package.json
  src/shared/components/bottom_navigation/BarcodeItem.tsx
  src/shared/components/bottom_navigation/BottomNavigation.tsx
  src/shared/components/bottom_navigation/barcode/BarcodeBottomSheet.tsx
  src/shared/components/bottom_navigation/barcode/BarcodeCropModal.tsx
  src/shared/components/bottom_navigation/barcode/BarcodeCropper.tsx
  src/shared/components/bottom_navigation/barcode/CroppedImg.tsx
  src/shared/components/buttons/ButtonBase.tsx
  src/shared/store/useImageCropStore.ts
  yarn.lock
Labels: ✨ 기능구현

#47 [UHYU-184][REFACTOR] 공통 파일 import 순서 정렬 적용
  src/pages/index.ts
  src/routes/AppRoutes.tsx
  src/shared/components/index.ts
  src/shared/store/index.ts
Labels: ♻️리펙토링

#41 [FEAT][UHYU-172] 지도 도메인 Zustnad + Context API 방식 리펙토링 + 커스텀 훅
  .gitignore
  src/features/kakao-map/api/mapApi.ts
  src/features/kakao-map/api/mockData.ts
  src/features/kakao-map/api/types.ts
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/kakao-map/components/MapContainer.tsx
  src/features/kakao-map/components/MapControlsContainer.tsx
  src/features/kakao-map/components/layout/StoreListContent.tsx
  src/features/kakao-map/components/layout/steps/BrandSelectContent.tsx
  src/features/kakao-map/components/location/LocationControlContainer.tsx
  src/features/kakao-map/components/marker/BrandMarker.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/context/MapContext.tsx
  src/features/kakao-map/context/MapUIContext.tsx
  src/features/kakao-map/hooks/useFilterNavigation.ts
  src/features/kakao-map/hooks/useMapControls.tsx
  src/features/kakao-map/hooks/useMapData.ts
  src/features/kakao-map/hooks/useMapInteraction.ts
  src/features/kakao-map/hooks/useMapQueries.ts
  src/features/kakao-map/hooks/useMapQueryies.ts
  src/features/kakao-map/hooks/useMapUI.ts
  src/features/kakao-map/hooks/useStoreSelection.ts
  src/features/kakao-map/store/LocationStore.ts
  src/features/kakao-map/store/MapStore.ts
  src/features/kakao-map/store/StoreListStore.ts
  src/features/kakao-map/store/types.ts
  src/features/kakao-map/types/store.ts
  src/features/kakao-map/utils/brandImageMapper.ts
  src/features/kakao-map/utils/categoryMapper.ts
  src/pages/map/MapPage.tsx
  tsconfig.tsbuildinfo
  yarn.lock
Labels: ♻️리펙토링

#48 [FEAT][UHYU-177] MSW 도입 및 지도 API 적용
  .gitignore
  package.json
  public/mockServiceWorker.js
  src/features/kakao-map/api/mapApi.ts
  src/main.tsx
  src/shared/msw/browser.ts
  src/shared/msw/handlers/index.ts
  src/shared/msw/handlers/map.ts
  src/shared/msw/index.ts
  yarn.lock
Labels: ✨ 기능구현

#50 [DOC][UHYU-186] AI/CodeRabbit 가이드라인 문서 추가
  .github/code_rabbit_rule.md
Labels: 📚 문서화

#49 [FEAT][UHYU-14] 지도 핵심 - 필터탭 기능 구현 (MOCK)
  .github/code_rabbit_rule.md
  src/features/kakao-map/api/types.ts
  src/features/kakao-map/components/MapControlsContainer.tsx
  src/features/kakao-map/components/layout/MapTopControls.tsx
  src/features/kakao-map/context/MapUIContext.tsx
  src/features/kakao-map/hooks/useMapData.ts
  src/features/kakao-map/hooks/useMapQueries.ts
  src/features/kakao-map/hooks/useMapUI.ts
  src/features/kakao-map/store/MapStore.ts
  src/shared/msw/handlers/map.ts
Labels: ✨ 기능구현

#52 [UHYU-190][REFACTOR] 지도 드래그 시 최소 이동 거리 및 거리 계산 로직으로 매장 검색 호출 이벤트 개선
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
Labels: ♻️리펙토링

#51 [CHORE][UHYU-70]Vercel을 위한 SPA fallback 라우팅
  vercel.json
Labels: ✨ 기능구현

#53 [FEAT][UHYU-185] 저장 시 자동 import 정렬 설정
  .prettierrc
  package.json
  src/features/benefit/components/BrandDetailModal.tsx
  src/features/benefit/components/CheckBoxList.tsx
  src/features/benefit/components/Pagination.tsx
  src/features/benefit/components/PaginationButton.tsx
  src/pages/benefit/BenefitPage.tsx
  src/shared/components/bottom_navigation/BottomNavigation.tsx
  src/shared/components/bottom_navigation/__stories__/BottomNavigation.stories.tsx
  src/shared/components/bottom_navigation/barcode/BarcodeBottomSheet.tsx
  src/shared/components/bottom_navigation/barcode/BarcodeCropModal.tsx
  src/shared/components/bottom_navigation/barcode/BarcodeCropper.tsx
  src/shared/components/bottom_navigation/barcode/CroppedImg.tsx
  src/shared/components/bottom_sheet/BaseBottomSheet.tsx
  src/shared/components/bottom_sheet/DragBottomSheet.tsx
  src/shared/components/bottom_sheet/NavigationBottomSheet.tsx
  src/shared/components/bottom_sheet/SelectionBottomSheet.tsx
  src/shared/components/bottom_sheet/__stories__/BaseBottomSheet.stories.tsx
  src/shared/components/bottom_sheet/__stories__/DragBottomSheet.stories.tsx
  src/shared/components/bottom_sheet/__stories__/NavigationBottomSheet.stories.tsx
  src/shared/components/bottom_sheet/__stories__/SelectionBottomSheet.stories.tsx
  src/shared/components/bottom_sheet/hooks/useBottomSheetNavigation.ts
  src/shared/components/brand_grid/BrandGrid.tsx
  src/shared/components/brand_grid/BrandLogo.tsx
  src/shared/components/brand_grid/__stories__/BrandGrid.stories.tsx
  src/shared/components/brand_grid/__stories__/GrandLogo.stories.tsx
  src/shared/components/buttons/ButtonBase.tsx
  src/shared/components/buttons/FileUploadButton.tsx
  src/shared/components/buttons/GhostButton.tsx
  src/shared/components/buttons/IconButton.tsx
  src/shared/components/buttons/NavButton.tsx
  src/shared/components/buttons/PrimaryButton.tsx
  src/shared/components/buttons/__stories__/FileUploadButton.stories.tsx
  src/shared/components/buttons/__stories__/GhostButton.stories.tsx
  src/shared/components/buttons/__stories__/IconButton.stories.tsx
  src/shared/components/buttons/__stories__/NavButton.stories.tsx
  src/shared/components/buttons/__stories__/PrimaryButton.stories.tsx
  src/shared/components/cards/BrandWithFavoriteCard.tsx
  src/shared/components/cards/__stories__/BrandCard.stories.tsx
  src/shared/components/cards/__stories__/BrandWithFavoriteCard.stories.tsx
  src/shared/components/cards/__stories__/CardBase.stories.tsx
  src/shared/components/filter_tabs/FilterTabs.tsx
  src/shared/components/filter_tabs/__stories__/FilterTabs.stories.ts
  src/shared/components/modals/BaseModal.tsx
  src/shared/components/modals/LoginModal.tsx
  src/shared/components/modals/ModalRoot.tsx
  src/shared/components/modals/__stories__/BaseModal.stories.tsx
  src/shared/components/modals/__stories__/LoginModal.stories.tsx
  src/shared/components/primary_checkbox/PrimaryCheckbox.tsx
  src/shared/components/primary_checkbox/__stories__/PrimaryCheckbox.stories.tsx
  src/shared/components/search_input/SearchInput.tsx
  src/shared/components/search_input/__stories__/SearchInput.stories.ts
  src/shared/lib/utils.ts
  src/shared/msw/browser.ts
  src/shared/msw/handlers/map.ts
  src/shared/store/useImageCropStore.ts
  yarn.lock
Labels: ✨ 기능구현

#54 [FEAT][UHYU-13] 지도 핵심 - 마커 클릭시 매장 상세 정보 인포윈도우 로직 구현
  .gitignore
  src/features/kakao-map/api/mockData.ts
  src/features/kakao-map/api/types.ts
  src/features/kakao-map/components/card/StoreDetailCard.tsx
  src/features/kakao-map/components/card/__stories__/StoreDetailCard.stories.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/components/marker/StoreInfoWindow.tsx
  src/shared/msw/handlers/map.ts
Labels: ✨ 기능구현

#57 [FEAT][UHYU-155] homePage MSW 적용 가이드
  src/features/home/api/endpoints.ts
  src/features/home/api/home.types.ts
  src/features/home/api/homeApi.ts
  src/features/home/api/mockData.ts
  src/features/home/components/auth/AuthBenefitsSection.tsx
  src/features/home/components/auth/AuthHeader.tsx
  src/features/home/components/auth/AuthHomeSheetContent.tsx
  src/features/home/components/auth/AuthNearbyStoresSection.tsx
  src/features/home/components/auth/AuthRecommendationList.tsx
  src/features/home/components/guest/GuestHeader.tsx
  src/features/home/components/guest/GuestHomeSheetContent.tsx
  src/features/home/components/guest/GuestNearbyStoresSection.tsx
  src/features/home/components/guest/GuestRecommendationList.tsx
  src/features/home/components/index.ts
  src/features/home/hooks/useBenefitsQuery.ts
  src/features/home/hooks/useNearbyStoresQuery.ts
  src/features/home/hooks/useUserInfoQuery.ts
  src/features/kakao-map/api/types.ts
  src/main.tsx
  src/pages/HomePage.tsx
  src/shared/client/ApiErrorResponse.ts
  src/shared/client/axiosClient.ts
  src/shared/client/client.type.ts
  src/shared/msw/handlers/home.ts
  src/shared/msw/handlers/index.ts
  src/shared/utils/createErrorResponse.ts
  src/shared/utils/createResponse.ts
  src/shared/utils/getErrorMessage.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ 기능구현

#55 [FEAT][UHYU-15] 지역 버튼 클릭시 해당 지역으로 이동 하는 로직
  src/features/home/api/homeApi.ts
  src/features/kakao-map/KakaoMap.tsx
  src/features/kakao-map/api/mapApi.ts
  src/features/kakao-map/api/mockData.ts
  src/features/kakao-map/api/types.ts
  src/features/kakao-map/components/MapControlsContainer.tsx
  src/features/kakao-map/components/card/StoreDetailCard.tsx
  src/features/kakao-map/components/card/__stories__/StoreDetailCard.stories.tsx
  src/features/kakao-map/components/layout/RegionFilterDropdown.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/components/marker/StoreInfoWindow.tsx
  src/features/kakao-map/constants/regions.ts
  src/features/kakao-map/hooks/useMapData.ts
  src/features/kakao-map/hooks/useMapQueries.ts
  src/shared/client/ApiErrorResponse.ts
  src/shared/client/client.type.ts
  src/shared/msw/handlers/home.ts
  src/shared/msw/handlers/map.ts
  src/shared/utils/createErrorResponse.ts
  src/shared/utils/createResponse.ts
Labels: ✨ 기능구현

#58 [REFACTOR][UHYU-197] 공통 응답 에러 부분 수정
  src/features/home/api/homeApi.ts
  src/shared/client/ApiErrorResponse.ts
  src/shared/client/axiosClient.ts
  src/shared/utils/getErrorMessage.ts
Labels: ♻️리펙토링

#60 [FIX][UHYU-193] 지도 핵심 - 즐겨찾기 기능 트러블 슈팅
  .github/workflows/chromatic.yml
  .github/workflows/develop.yml
  public/mockServiceWorker.js
  src/features/kakao-map/api/mapApi.ts
  src/features/kakao-map/api/mockData.ts
  src/features/kakao-map/api/types.ts
  src/features/kakao-map/components/card/StoreDetailCard.tsx
  src/features/kakao-map/components/layout/StoreListContent.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/components/marker/StoreInfoWindow.tsx
  src/features/kakao-map/hooks/useMapData.ts
  src/features/kakao-map/hooks/useMapQueries.ts
  src/features/kakao-map/types/store.ts
  src/features/user/api/userApi.ts
  src/shared/client/axiosClient.ts
  src/shared/components/buttons/__stories__/GhostButton.stories.tsx
Labels: 🐞 버그

#62 [FEAT][UHYU-202] 로그인 버튼 임시구현
  src/features/home/components/LoginButton.tsx
  src/pages/HomePage.tsx
Labels: ✨ 기능구현

#61 [FEAT][UHYU-194] 제휴처 목록 조회 MSW 및 기능 구현
  .prettierrc
  .storybook/main.ts
  README.md
  src/features/benefit/api/benefitApi.ts
  src/features/benefit/api/endpoints.ts
  src/features/benefit/api/mockData.ts
  src/features/benefit/api/types.ts
  src/features/benefit/components/BenefitHeader.tsx
  src/features/benefit/components/BenefitList.tsx
  src/features/benefit/components/BrandDetailModal.tsx
  src/features/benefit/components/CheckBoxList.tsx
  src/features/benefit/components/Pagination.tsx
  src/features/benefit/components/PaginationButton.tsx
  src/features/benefit/components/index.ts
  src/features/benefit/hooks/useBenefitQueryParams.ts
  src/features/benefit/hooks/useGetBrandListQuery.ts
  src/features/benefit/types/BrandDetail.types.ts
  src/features/benefit/types/Pagination.types.ts
  src/features/benefit/types/PaginationButton.types.ts
  src/features/benefit/types/component.ts
  src/features/benefit/types/index.ts
  src/features/benefit/types/queryParams.ts
  src/features/benefit/utils/parseQueryParams.ts
  src/features/home/components/auth/AuthHomeSheetContent.tsx
  src/features/home/components/guest/GuestHomeSheetContent.tsx
  src/features/home/hooks/useUserInfoQuery.ts
  src/features/kakao-map/components/layout/MapTopControls.tsx
  src/features/kakao-map/components/layout/StoreListContent.tsx
  src/pages/HomePage.tsx
  src/pages/benefit/BenefitPage.tsx
  src/pages/map/MapPage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/MyPageActivity.tsx
  src/shared/components/filter_tabs/FilterTabs.variants.ts
  src/shared/msw/handlers/benefit.ts
  src/shared/msw/handlers/index.ts
  src/shared/msw/handlers/map.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ 기능구현

#72 [FEAT][UHYU-213] 즐겨찾기 + My Map 목록 조회 MSW 및 기능
  src/features/benefit/api/mockData.ts
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/kakao-map/components/layout/PersistentBottomSheet.tsx
  src/features/kakao-map/context/MapUIContext.tsx
  src/features/kakao-map/hooks/useMapUI.ts
  src/features/mymap/api/endpoint.ts
  src/features/mymap/api/mockData.ts
  src/features/mymap/api/mymapApi.ts
  src/features/mymap/api/types.ts
  src/features/mymap/components/mymap-list/ADDMyMapButton.tsx
  src/features/mymap/components/mymap-list/MyMapList.tsx
  src/features/mymap/components/mymap-list/index.ts
  src/features/mymap/constants/mymapColor.ts
  src/features/mymap/hooks/useMyMapListQuery.ts
  src/index.css
  src/shared/msw/handlers/benefit.ts
  src/shared/msw/handlers/index.ts
  src/shared/msw/handlers/mymap.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ 기능구현

#70 [FEAT][UHYU-204] 바코드 켰을때 위치 처리 기반 API 로직 구현
  src/features/barcode/api/barcode.type.ts
  src/features/barcode/api/endpoints.ts
  src/features/barcode/api/nearbyStoreApi.ts
  src/features/barcode/api/visitStoreApi.ts
  src/features/barcode/components/VisitConfirmModal.tsx
  src/features/barcode/hooks/useNearbyStore.ts
  src/features/barcode/hooks/useVisitConfirmMutation.ts
  src/pages/HomePage.tsx
  src/shared/components/bottom_navigation/barcode/BarcodeBottomSheet.tsx
  src/shared/msw/handlers/index.ts
  src/shared/msw/handlers/visitstore.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ 기능구현

#74 [FEAT][UHYU-192] 지도 바텀 시트 브랜드 필터 기능 구현
  public/images/brands/default-brand-logo.png
  src/App.tsx
  src/features/extra-info/components/StepContent.tsx
  src/features/kakao-map/api/endpoints.ts
  src/features/kakao-map/api/mapApi.ts
  src/features/kakao-map/api/mockData.ts
  src/features/kakao-map/api/types.ts
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/kakao-map/components/MapDragBottomSheet.tsx
  src/features/kakao-map/constants/categoryMapping.ts
  src/features/kakao-map/hooks/useBrandsByCategory.ts
  src/features/kakao-map/hooks/useMapQueries.ts
  src/features/kakao-map/hooks/useMapUI.ts
  src/features/kakao-map/types/category.ts
  src/features/mypage/api/mockData.ts
  src/features/mypage/api/types.ts
  src/features/mypage/components/MyPageHeader.tsx
  src/features/mypage/components/MyPageMarker.tsx
  src/features/mypage/components/MyPageUserInfo.tsx
  src/features/mypage/types/mockUser.ts
  src/features/mypage/types/types.ts
  src/features/user/api/types.ts
  src/pages/map/MapPage.tsx
  src/shared/components/BaseLayout.tsx
  src/shared/components/brand_grid/BrandGrid.tsx
  src/shared/components/brand_grid/__stories__/BrandGrid.stories.tsx
  src/shared/components/brand_grid/brand.type.ts
  src/shared/components/filter_tabs/FilterTabs.variants.ts
  src/shared/msw/handlers/map.ts
  src/shared/msw/handlers/mypage.ts
  src/shared/store/useUserStore.ts
Labels: ✨ 기능구현, ♻️리펙토링

#76 [REFACTOR][UHYU-234] 브랜드 요청 형식 변경 및 온보딩 요청 적용
  src/features/extra-info/components/StepContent.tsx
  src/features/extra-info/hooks/useSignupFlow.ts
  src/features/extra-info/types/index.ts
  src/features/mypage/api/mockData.ts
  src/features/mypage/api/types.ts
  src/features/mypage/types/mockUser.ts
  src/features/user/api/types.ts
  src/shared/components/brand_grid/BrandGrid.tsx
  src/shared/components/brand_grid/brand.type.ts
Labels: ♻️리펙토링

#75 [FEAT][UHYU-50] 관리자 페이지 msw-api 연결
  src/features/admin/api/adminApi.ts
  src/features/admin/api/endpoints.ts
  src/features/admin/api/index.ts
  src/features/admin/api/mockData.ts
  src/features/admin/api/types.ts
  src/pages/admin/AdminPage.tsx
  src/pages/index.ts
  src/routes/AppRoutes.tsx
  src/routes/path.ts
  src/shared/msw/handlers/admin.ts
  src/shared/msw/handlers/index.ts
Labels: ✨ 기능구현

#79 [FEAT][UHYU-224] mymap 추가, 수정, 삭제 MSW 및 기능구현
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/mymap/api/mymapApi.ts
  src/features/mymap/api/types.ts
  src/features/mymap/components/InputMymap.tsx
  src/features/mymap/components/MymapDeleteModal.tsx
  src/features/mymap/components/ShareModal.tsx
  src/features/mymap/components/mymap-list/ADDMyMapButton.tsx
  src/features/mymap/components/mymap-list/MyMapList.tsx
  src/features/mymap/components/mymap-list/index.ts
  src/features/mymap/hooks/useAddMyMapMutation.ts
  src/features/mymap/hooks/useDeleteMyMapMutation.ts
  src/features/mymap/hooks/useUpdateMyMapMutation.ts
  src/shared/msw/handlers/mymap.ts
Labels: ✨ 기능구현

#78 [FEAT][UHYU-235] 지도 핵심 - 일정 거리 이상 지도 이동 시 재검색 버튼 기능
  README.md
  src/features/kakao-map/components/ManualSearchButton.tsx
  src/features/kakao-map/components/MapContainer.tsx
  src/features/kakao-map/components/SearchModeToggle.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/hooks/useManualSearch.ts
  src/pages/map/MapPage.tsx
Labels: ✨ 기능구현

#81 [FEAT][UHYU-222] 지도 화면에서 로그인 여부 확인 및 모달 로직 구현 ( 즐겨찾기 라우트 연결 )
  src/features/home/components/LoginButton.tsx
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/mymap/api/mockData.ts
  src/features/mymap/api/types.ts
  src/features/mymap/components/mymap-list/AddMyMapButton.tsx
  src/features/mymap/components/mymap-list/MyMapList.tsx
  src/shared/components/modals/LoginModal.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useKakaoLogin.ts
  src/shared/msw/handlers/mymap.ts
Labels: ✨ 기능구현

#83 [FIX][UHYU-236] bottom sheet 동작 기능 픽스 (매장 클릭 시, 리스트 클릭 시), 바텀시트 상태관리 이슈
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/kakao-map/components/MapContainer.tsx
  src/features/kakao-map/components/MapControlsContainer.tsx
  src/features/kakao-map/components/MapDragBottomSheet.tsx
  src/features/kakao-map/components/layout/MapTopControls.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/hooks/useMapInteraction.ts
  src/pages/map/MapPage.tsx
Labels: ♻️리펙토링, 🐞 버그

#86 [FEAT][UHYU-226] mymap 매장 추가/삭제, 매장 등록 유무 조회 MSW 및 AddStore 컴포넌트 구현
  src/features/mymap/api/mockData.ts
  src/features/mymap/api/mymapApi.ts
  src/features/mymap/api/types.ts
  src/features/mymap/components/mymap-add-store/AddStore.tsx
  src/features/mymap/hooks/useStoreBookmarkStatusQuery.ts
  src/features/mymap/hooks/useToggleMyMapStoreMutation.ts
  src/shared/msw/handlers/mymap.ts
  yarn.lock
Labels: ✨ 기능구현

#89 [FIX][UHYU-241] auth redirect
  src/App.tsx
  src/features/user/api/endpoints.ts
  src/features/user/api/types.ts
  src/features/user/api/userApi.ts
  src/shared/store/useUserStore.ts
Labels: 🐞 버그

#88 #86 #87 PR 병합 진행, bottom sheet 리펙토링 및 MyMap UI 추가 기능
  .claude/settings.local.json
  package.json
  public/mockServiceWorker.js
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/kakao-map/components/MapContainer.tsx
  src/features/kakao-map/components/MapControlsContainer.tsx
  src/features/kakao-map/components/MapDragBottomSheet.tsx
  src/features/kakao-map/components/layout/PersistentBottomSheet.tsx
  src/features/kakao-map/context/MapUIContext.tsx
  src/features/kakao-map/hooks/useMapInteraction.ts
  src/features/kakao-map/hooks/useMapUI.ts
  src/features/mymap/components/mymap-add-store/AddStore.tsx
  src/features/user/api/types.ts
  src/pages/map/MapPage.tsx
  src/shared/store/useUserStore.ts
  yarn.lock
Labels: ✨ 기능구현

#97 [FEAT][UHYU-245] AddStore 컴포넌트 즐겨찾기 api 연동 및 UX 수정
  src/features/mymap/components/mymap-add-store/AddStore.tsx
  src/features/mymap/components/mymap-list/AddMyMapButton.tsx
Labels: ✨ 기능구현, ♻️리펙토링

#98 [FEAT][UHYU-248] userStore 새로 등록
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/kakao-map/components/SidebarSheet.tsx
  src/features/kakao-map/components/layout/StoreListContent.tsx
  src/features/recommendation/components/RecommendedStoreList.tsx
  src/features/user/components/LogoutButton.tsx
  src/features/user/hooks/useUserMutation.ts
  src/shared/components/bottom_navigation/barcode/BarcodeBottomSheet.tsx
  src/shared/store/useUserStore.ts
  src/shared/store/userStore.ts
  yarn.lock
Labels: ♻️리펙토링

#99 [REFACTOR][UHYU-248] user 관련 필요없는 파일 삭제 및 바코드 오류 수정
  src/features/user/api/types.ts
  src/shared/components/bottom_navigation/barcode/contents/LoggedInBarcodeContent.tsx
  src/shared/store/useUserStore.ts
  src/shared/utils/isApiError.ts
Labels: ♻️리펙토링

#101 [UHYU-247][FIX] 매장 즐겨찾기 url 명세에 맞게 수정
  src/features/kakao-map/api/endpoints.ts
  src/features/kakao-map/api/mapApi.ts
  src/shared/msw/handlers/map.ts
  yarn.lock
Labels: 🐞 버그

#100 [FEAT][UHYU-249] 공유 지도(/map/:uuid) 상세 뷰 구현 및 상태 연동
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/mymap/api/mockData.ts
  src/features/mymap/api/types.ts
  src/features/mymap/components/StoreDeleteModal.tsx
  src/features/mymap/components/mymap-uuid/MymapUuid.tsx
  src/features/mymap/hooks/useInitSharedMap.ts
  src/features/mymap/store/SharedMapStore.ts
  src/routes/AppRoutes.tsx
  src/shared/msw/handlers/mymap.ts
Labels: ✨ 기능구현

#104 [BUG][UHYU-270] mymaplist에 data가 없는 경우 처리
  src/features/mymap/api/mymapApi.ts
  src/features/mymap/components/mymap-list/MyMapList.tsx
Labels: 🐞 버그

#105 [FIX][UHYU-266] 마이페이지 접근 에러 해결 및 api 요청 방식 수정
  src/features/mypage/api/endpoints.ts
  src/features/mypage/api/mockData.ts
  src/features/mypage/api/mypageApi.ts
  src/features/mypage/api/types.ts
  src/features/mypage/components/ActivityBenefit.tsx
  src/features/mypage/components/ActivityBrands.tsx
  src/features/mypage/components/MyPageBrand.tsx
  src/features/mypage/components/MyPageHeader.tsx
  src/features/mypage/components/MyPageMarker.tsx
  src/features/mypage/components/MyPageMembership.tsx
  src/features/mypage/components/MyPageUserInfo.tsx
  src/features/mypage/constants/gradeUtils.ts
  src/features/mypage/hooks/useActivityQuery.ts
  src/features/mypage/hooks/useUserInfoQuery.ts
  src/features/mypage/types/mockActivity.ts
  src/features/mypage/utils/dateUtils.ts
  src/pages/mypage/MyPage.tsx
  src/shared/msw/handlers/mypage.ts
  yarn.lock
Labels: 🐞 버그

#106 [REFACTOR][UHYU-268] 바코드 이미지 zustand 관리, 위치정보 api 수정
  src/features/barcode/api/endpoints.ts
  src/features/barcode/api/getNearbyStores.ts
  src/features/barcode/api/nearbyStoreApi.ts
  src/features/barcode/components/VisitConfirmSection.tsx
  src/features/barcode/hooks/useBarcodeImageQuery.ts
  src/features/barcode/hooks/useNearbyStore.ts
  src/features/barcode/hooks/useNearbyStoreQuery.ts
  src/shared/components/bottom_navigation/barcode/BarcodeCropModal.tsx
  src/shared/components/bottom_navigation/barcode/CroppedImg.tsx
  src/shared/components/bottom_navigation/barcode/contents/LoggedInBarcodeContent.tsx
  src/shared/msw/handlers/index.ts
  src/shared/msw/handlers/visitstore.ts
  src/shared/store/barcodeStore.ts
Labels: ♻️리펙토링

#109 [FIX][UHYU-268] 바코드 이미지 재업로드 수정
  src/features/barcode/hooks/useBarcodeImageQuery.ts
  src/shared/components/bottom_navigation/barcode/BarcodeCropModal.tsx
  src/shared/components/bottom_navigation/barcode/contents/LoggedInBarcodeContent.tsx
  yarn.lock
Labels: 🐞 버그

#102 [FIX][UHYU-250] 바텀시트 높이 반응형 도입 및 바텀 네비게이션 반응형 도입
  .claude/settings.local.json
  .gitignore
  src/features/kakao-map/components/ManualSearchButton.tsx
  src/features/kakao-map/components/MapDragBottomSheet.tsx
  src/index.css
  src/shared/components/AppInitializer.tsx
  src/shared/utils/scrollRestore.ts
  src/shared/utils/viewport.ts
Labels: 🐞 버그

#110 [FEAT][UHYU-277] mymap page
  src/features/mymap/components/MymapBody.tsx
  src/features/mymap/components/MymapHeader.tsx
  src/pages/index.ts
  src/pages/mymap/MymapPage.tsx
  src/routes/AppRoutes.tsx
  src/routes/path.ts
  src/shared/components/bottom_navigation/BottomNavigation.tsx
Labels: ✨ 기능구현

#111 [FEAT][UHYU-269]addmymap 모달 닫기 추가 및 앱라우터 수정
  src/features/mymap/components/mymap-add-store/AddStore.tsx
  src/routes/AppRoutes.tsx
Labels: ✨ 기능구현

#107 [FEAT][REFACTOR][UHYU-259][UHYU-225] 권한별 프로텍트 라우트, 로그인 모달 개선, 바텀 네비게이션 활성화 로직 개선
  src/features/home/api/home.types.ts
  src/features/home/api/mockData.ts
  src/features/home/components/auth/AuthHeader.tsx
  src/features/kakao-map/api/mockData.ts
  src/features/mypage/api/mockData.ts
  src/features/mypage/api/types.ts
  src/features/mypage/types/mockUser.ts
  src/features/user/api/types.ts
  src/features/user/hooks/useUserMutation.ts
  src/features/user/index.ts
  src/routes/AppRoutes.tsx
  src/shared/components/AppInitializer.tsx
  src/shared/components/bottom_navigation/BarcodeItem.tsx
  src/shared/components/bottom_navigation/BottomNavigation.tsx
  src/shared/components/bottom_navigation/NavItem.tsx
  src/shared/components/bottom_navigation/NavItem.types.ts
  src/shared/components/index.ts
  src/shared/components/modals/BaseModal.tsx
  src/shared/components/modals/LoginModal.tsx
  src/shared/components/route/ProtectedRoute.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useAuthCheckModal.ts
  src/shared/store/modalStore.ts
  src/shared/store/userStore.ts
  src/shared/types/index.ts
  src/shared/types/user.ts
Labels: ✨ 기능구현, ♻️리펙토링, 🐞 버그

#112 [FEAT][UHYU-276] 활동내역 msw 방식 api 연결
  src/features/mypage/api/endpoints.ts
  src/features/mypage/api/mockData.ts
  src/features/mypage/api/mypageApi.ts
  src/features/mypage/api/types.ts
  src/features/mypage/components/ActivityBenefit.tsx
  src/features/mypage/components/ActivityBrands.tsx
  src/features/mypage/components/ActivityFavorite.tsx
  src/features/mypage/components/ActivityTabs.tsx
  src/features/mypage/hooks/useActivityQuery.ts
  src/features/mypage/hooks/useUserInfoQuery.ts
  src/features/mypage/types/mockActivity.ts
  src/features/mypage/types/mockUser.ts
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/MyPageActivity.tsx
  src/shared/msw/handlers/mypage.ts
  yarn.lock
Labels: ✨ 기능구현

#117 [FEAT][UHYU-288] mymap kakao 공유하기 기능
  index.html
  public/images/share/kakao.png
  public/images/share/share.png
  public/images/share/url.png
  src/features/mymap/components/ShareModal.tsx
  src/features/mymap/hooks/useKakaoShare.ts
  src/vite-env.d.ts
Labels: ✨ 기능구현

#119 [UHYU-296][FIX] 사용하지 않는 export 제거
  src/features/kakao-map/components/search/index.ts
  src/shared/components/route/ProtectedRoute.tsx
Labels: 🐞 버그

#120 [FEAT][UHYU-279] 제휴 매장 인포윈도우 긴글 처리 (더보기 로직) 및 애니메이션 도입
  src/features/kakao-map/api/mockData.ts
  src/features/kakao-map/components/card/StoreDetailCard.tsx
  src/features/kakao-map/components/marker/BrandMarker.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/components/marker/StoreInfoWindow.tsx
Labels: ✨ 기능구현

#123 [FIX]logo_image 타입 수정
  src/features/home/api/home.types.ts
  src/features/home/api/mockData.ts
  src/features/kakao-map/api/mockData.ts
  src/features/kakao-map/api/types.ts
  src/features/kakao-map/components/layout/StoreListContent.tsx
  src/features/kakao-map/components/marker/BrandMarker.tsx
  src/features/kakao-map/types/store.ts
  src/features/mymap/api/mockData.ts
  src/features/mymap/api/types.ts
  src/features/mymap/components/mymap-uuid/MymapUuid.tsx
  src/features/recommendation/api/recommendedStores.mock.ts
  src/features/recommendation/api/recommendedStores.types.ts
  src/features/recommendation/components/RecommendedCard.tsx
Labels: ♻️리펙토링

#121 [FEAT][UHYU-289]mymap 이전 버튼 생성 및 ui 수정
  src/features/benefit/components/BenefitList.tsx
  src/features/benefit/components/BrandDetailModal.tsx
  src/features/benefit/hooks/index.ts
  src/features/kakao-map/components/BottomSheetContainer.tsx
  src/features/kakao-map/components/marker/StoreInfoWindow.tsx
  src/features/mymap/components/AddMyMapButton.tsx
  src/features/mymap/components/bottom-sheet/MyMapList.tsx
  src/features/mymap/components/bottom-sheet/MymapUuid.tsx
  src/features/mymap/components/index.ts
  src/features/mymap/components/list/MymapBody.tsx
  src/features/mymap/components/list/MymapHeader.tsx
  src/features/mymap/components/modal/AddStoreModal.tsx
  src/features/mymap/components/modal/MyMapFormModal.tsx
  src/features/mymap/components/modal/MymapDeleteModal.tsx
  src/features/mymap/components/modal/ShareModal.tsx
  src/features/mymap/components/modal/StoreDeleteModal.tsx
  src/features/mymap/components/mymap-list/index.ts
  src/features/mymap/hooks/index.ts
  src/features/mymap/store/SharedMapStore.ts
  src/pages/mymap/MymapPage.tsx
  src/shared/components/bottom_sheet/BaseBottomSheet.tsx
  src/shared/components/buttons/BackButton.tsx
  src/shared/components/buttons/__stories__/BackButton.stories.tsx
  src/shared/components/filter_tabs/FilterTabs.tsx
  src/shared/components/filter_tabs/FilterTabs.variants.ts
  src/shared/components/index.ts
  src/shared/hooks/useCanGoBack.ts
Labels: ✨ 기능구현

#125 [FEAT][UHYU-302] speed-insights 추가
  package.json
  src/main.tsx
  yarn.lock
Labels: ✨ 기능구현

#128 [FEAT][UHYU-306] 마커 클릭 ( 매장 상세 정보 조회 인포윈도우 ) 시 로그인 여부 확인 및 로그인 모달 로직
  public/images/kakao-login/kakao_login_medium_wide.png
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/shared/components/buttons/KakaoLoginButton.tsx
  src/shared/components/index.ts
  src/shared/components/modals/LoginModal.tsx
  src/shared/store/userStore.ts
Labels: ✨ 기능구현, ♻️리펙토링

#127 [FEAT][UHYU-301] 혜택, mymap 스켈레톤 및 새 지도 만들기 삭제
  src/features/benefit/components/BenefitList.tsx
  src/features/mymap/components/bottom-sheet/MyMapList.tsx
  src/features/mymap/components/bottom-sheet/MymapUuid.tsx
  src/features/mymap/components/list/MymapBody.tsx
  src/features/mymap/components/modal/AddStoreModal.tsx
  src/shared/components/Skeleton/SkeletonBrandCard.tsx
  src/shared/components/Skeleton/SkeletonMyMapItem.tsx
  src/shared/components/Skeleton/SkeletonMyMapUuidItem.tsx
  src/shared/components/Skeleton/index.ts
Labels: ✨ 기능구현

#129 [FEAT][UHYU-307] 공유 지도(/map/:uuid)에서 검색창 및 필터 숨김 처리
  src/features/kakao-map/components/MapControlsContainer.tsx
Labels: ✨ 기능구현

#130 [FEAT]/[UHYU-299] 관리자 페이지 통계 UI
  src/App.tsx
  src/features/admin/api/adminApi.ts
  src/features/admin/api/mockData.ts
  src/features/admin/api/types.ts
  src/features/admin/components/brand/AdminBrandForm.tsx
  src/features/admin/components/brand/AdminBrandList.tsx
  src/features/admin/components/brand/AdminBrandModal.tsx
  src/features/admin/components/common/AdminToggleTabs.tsx
  src/features/admin/components/common/CategoryFilter.tsx
  src/features/admin/components/common/StatsSummaryCards.tsx
  src/features/admin/components/common/StatsTabButtons.tsx
  src/features/admin/components/common/index.ts
  src/features/admin/components/stats/BookmarkChart.tsx
  src/features/admin/components/stats/FilteringChart.tsx
  src/features/admin/components/stats/MembershipChart.tsx
  src/features/admin/components/stats/RecommendChart.tsx
  src/features/admin/components/stats/TotalStatsCard.tsx
  src/features/admin/constants/categories.ts
  src/features/admin/hooks/index.ts
  src/features/admin/hooks/useAdminBrandMutation.ts
  src/features/admin/hooks/useAdminBrandQuery.ts
  src/features/admin/hooks/useAdminStatsQuery.ts
  src/features/admin/index.ts
  src/features/admin/types/component.ts
  src/features/admin/types/index.ts
  src/features/admin/utils/categoryMapping.ts
  src/features/admin/utils/categoryUtils.ts
  src/features/mypage/api/mockData.ts
  src/features/user/hooks/useUserQuery.ts
  src/index.css
  src/pages/admin/AdminPage.tsx
  src/routes/AppRoutes.tsx
  src/shared/components/AppInitializer.tsx
  src/shared/components/bottom_navigation/BottomNavigation.tsx
  src/shared/components/route/ProtectedRoute.tsx
  src/shared/msw/handlers/admin.ts
  src/shared/store/userStore.ts
  yarn.lock
Labels: ✨ 기능구현

#131 [FEAT][UHYU-308] 등급별 혜택 디코딩 및 파싱 로직 개선
  package.json
  src/features/benefit/api/mockData.ts
  src/features/benefit/components/BenefitList.tsx
  src/features/benefit/components/BrandDetailModal.tsx
  src/features/benefit/utils/formatGradeDescriptions.tsx
  src/features/benefit/utils/formatUsageText.ts
  src/shared/utils/formatNewlines.tsx
  yarn.lock
Labels: ✨ 기능구현

#132 [FEAT][UHYU-315] 관리자 페이지 브랜드 관리 UI
  src/features/admin/api/mockData.ts
  src/features/admin/api/types.ts
  src/features/admin/components/brand/AdminBrandCard.tsx
  src/features/admin/components/brand/AdminBrandForm.tsx
  src/features/admin/components/brand/AdminBrandModal.tsx
  src/features/admin/components/brand/BrandForm.tsx
  src/features/admin/components/brand/BrandListItem.tsx
  src/features/admin/components/brand/NewAdminBrandList.tsx
  src/features/admin/components/brand/index.ts
  src/features/admin/components/common/CategoryFilter.tsx
  src/features/admin/components/stats/BookmarkChart.tsx
  src/features/admin/components/stats/FilteringChart.tsx
  src/features/admin/components/stats/MembershipChart.tsx
  src/features/admin/components/stats/RecommendChart.tsx
  src/features/admin/constants/categories.ts
  src/features/admin/hooks/index.ts
  src/features/admin/hooks/useAdminBrandMutation.ts
  src/features/admin/utils/categoryMapping.ts
  src/features/admin/utils/categoryUtils.ts
  src/index.css
  src/pages/admin/AdminPage.tsx
  src/shared/msw/handlers/admin.ts
  yarn.lock
Labels: ✨ 기능구현

#133 [FEAT][UHYU-67] recommend 카드 구현
  public/images/recommendation/empty-state-2.png
  src/features/kakao-map/components/layout/StoreListContent.tsx
  src/features/kakao-map/components/marker/BrandMarker.tsx
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/hooks/useMapData.ts
  src/features/kakao-map/store/MapStore.ts
  src/features/kakao-map/store/types.ts
  src/features/recommendation/Recommendation.types.ts
  src/features/recommendation/api/endpoints.ts
  src/features/recommendation/api/recommendedStores.mock.ts
  src/features/recommendation/api/recommendedStores.types.ts
  src/features/recommendation/api/recommendedStoresApi.ts
  src/features/recommendation/components/GuestCard.tsx
  src/features/recommendation/components/RecommendedCard.tsx
  src/features/recommendation/components/RecommendedStoreList.tsx
  src/features/recommendation/components/RecommendedStoreListGuest.tsx
  src/features/recommendation/components/RecommendedStoreListLoggedIn.tsx
  src/features/recommendation/components/RecommendedStoreListWrapper.tsx
  src/features/recommendation/components/StoreInfoWindow.tsx
  src/features/recommendation/components/ToggleButton.tsx
  src/features/recommendation/components/index.ts
  src/features/recommendation/hooks/useRecommendQuery.ts
  src/shared/msw/handlers/index.ts
  src/shared/msw/handlers/recommendation.ts
  yarn.lock
Labels: ✨ 기능구현

#135 [FEAT][UHYU-316] 공유 지도 전용 마커 컴포넌트 MyMapMarker 생성 및 적용
  src/features/kakao-map/components/marker/MapWithMarkers.tsx
  src/features/kakao-map/components/marker/MyMapMarker.tsx
  src/features/mymap/api/mockData.ts
Labels: ✨ 기능구현, 🐞 버그

#143 [REFACTOR][UHYU-325] 필터탭 패딩 제거 및 스크롤 이벤트 방지
  src/features/benefit/components/BenefitList.tsx
  src/features/kakao-map/components/layout/MapTopControls.tsx
  src/shared/components/filter_tabs/FilterTabs.tsx
  yarn.lock
Labels: ♻️리펙토링

#146 [BUG][UHYU-326] fix: 파일명 변경 적용
  src/features/benefit/components/BenefitList.tsx
  src/features/benefit/components/BrandDetailModal.tsx
  src/features/mymap/components/bottom-sheet/MyMapList.tsx
  src/features/mymap/components/bottom-sheet/MymapUuid.tsx
  src/features/mymap/components/list/MymapBody.tsx
Labels: 🐞 버그

#147 [FEAT][UHYU-67] 로그인 분기처리 수정 및 스피너 추가
  package.json
  src/features/recommendation/components/RecommendedStoreListLoggedIn.tsx
  src/features/recommendation/components/RecommendedStoreListWrapper.tsx
  yarn.lock
Labels: 🐞 버그
